easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      list:
        actions:
          - {name: 'show', icon: 'eye', label: false, css_class: 'btn btn-primary'}
          - {name: 'edit', icon: 'paint-brush', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        # item_permission: 'ROLE_ADMIN'
      form:
        fields:
          - {property: 'name', label: 'Nom de la cat√©gorie'}